---
- name: Update system
  apt:
    name: "*"
    state: latest
    update_cache: yes
    autoremove: yes
  tags:
   - os_config

- name: Get OMV installation script
  get_url:
    url: https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install
    dest: /tmp/omv_install
    mode: '0774'

- name: Install Open Media Vault
  shell: bash /tmp/omv_install