---
- name: Initiall configuration
  hosts: localhost
  gather_facts: yes
  user: przemek
  become: yes
  
  pre_tasks:
  - name: check connectivity
    ping:

  tasks:
  - import_role:
      name: prometheus_grafana
      tasks_from: main.yml