---
- name: Update system
  apt:
    name: "*"
    state: latest
    update_cache: yes
    autoremove: yes
  tags:
   - os_config

- name: Install OS packages
  apt:
    name: "{{ packages }}"
    state: present
  tags:
   - os_config

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
   - os_config

- name: Update /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host].inventory_hostname }} {{ host }}
      {% endfor %}
  tags:
   - os_config

- name: change user pi password
  user:
    name: pi
    password: "{{ pi_pass }}"
  no_log: True
  tags:
   - os_config

- name: Update MOTD messages
  block:
    - name: Copy new MOTD script
      copy:
        src: ../motd/11-sysinfo
        dest: /etc/update-motd.d/11-sysinfo
        mode: '0755'
        owner: root
        group: root
    - name: Clean /etc/motd file
      copy:
        content: ""
        dest: /etc/motd

- name: Control fan speed
  ansible.builtin.blockinfile:
    path: /boot/config.txt
    block: |
      dtparam=poe_fan_temp0=50000
      dtparam=poe_fan_temp1=60000
      dtparam=poe_fan_temp2=70000
      dtparam=poe_fan_temp3=80000