---
- name: Update system
  apt:
    name: "*"
    state: latest
    update_cache: yes
    autoremove: yes
  tags:
   - os_config

- name: Install OS packages
  apt:
    name: "{{ packages }}"
    state: present
  tags:
   - os_config

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
   - os_config

- name: Update /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host].inventory_hostname }} {{ host }}
      {% endfor %}
  tags:
   - os_config

- name: change user pi password
  user:
    name: pi
    password: "{{ pi_pass }}"
  no_log: True
  tags:
   - os_config