---
- name: Collectd agent installation
  hosts: all
  gather_facts: yes
  user: przemek
  become: yes
  
  pre_tasks:
  - name: check connectivity
    ping:

  tasks:
  - import_role:
      name: influxdb_grafana
      tasks_from: main.yml