version: '3.8'

networks: 
  tooling:
    external: true
    driver: bridge
    
volumes:
  traefik-ssl-certs:
    driver: local

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    networks:
      - tooling
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      DYNU_API_KEY: ${DYNU_API_KEY}
    restart: unless-stopped 
    volumes:
      - /var/log/traefik:/var/log/traefik
      - traefik-ssl-certs:/letsencrypt
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
