version: '3.8'

networks:
  monitoring:
    name: monitoring
    external: true

volumes:
  traefik-ssl-certs:
    driver: local

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    networks:
      - monitoring
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      DYNU_API_KEY: ${DYNU_API_KEY}
    restart: unless-stopped 
    volumes:
      - traefik-ssl-certs:/letsencrypt
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
