---
version: '3.8'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped    
    networks:
      - monitoring
    ports:
      - "9100:9100"
    volumes:
      - '/:/host:ro,rslave'

networks:
  monitoring:
    name: monitoring
    external: true