---
- name: PRE-CONFIG
  hosts: all
  gather_facts: true
  user: przemek
  become: true
  become_user: root

  vars_files:
    - vars.yml
    - ../../vault.yml

  pre_tasks:
    - action: ping

  tasks:
    - name: Update system
      apt:
        name: "*"
        state: latest
        update_cache: true
        autoremove: true
    - name: Make tooling directory
      file:
        state: directory
        path: "{{ tooling_directory }}"
        owner: root
        group: root
        mode: '0770'
    - name: Make nextcloud DATA directories
      file:
        state: directory
        path: "{{ item }}"
        owner: www-data
        group: www-data
        mode: '2775'  # guid
      with_items:
        - "{{ tooling_directory }}/{{ nextcloud_directory }}"
        - "{{ data_directories[0] }}"
        - "{{ data_directories[2] }}"
    - name: Make nextcloud DB directories
      file:
        state: directory
        path: "{{ item }}"
        owner: '999'
        group: spi
        mode: '2775'  # guid
      with_items:
        - "{{ data_directories[1] }}"
    - name: Create docker network {{ docker_network }}
      docker_network:
        name: "{{ docker_network }}"

- name: NEXTCLOUD CONFIGURATION
  hosts: all
  gather_facts: true
  user: przemek
  become: true
  become_user: root

  vars_files:
    - ../../vault.yml
    - vars.yml

  tasks:
    - name: Copy nextcloud docker-compose file
      template:
        src: ../templates/nextcloud/nextcloud.j2
        dest: "{{ tooling_directory }}/{{ nextcloud_directory }}/docker-compose.yml"
        owner: root
        group: root
        mode: '0750'
    - name: Start Nextcloud
      ansible.builtin.shell:
        cmd: docker-compose up -d
        chdir: "{{ tooling_directory }}/{{ nextcloud_directory }}"
    - name: Get {{ nextcloud_app_container_name }} container info
      docker_container_info:
        name: "{{ nextcloud_app_container_name }}"
      register: result
    - name: Print the status of the {{ nextcloud_app_container_name }} container
      debug:
        msg: |
          State: {{ result.container['State']['Status'] }}
          Started: {{ result.container['State']['StartedAt'] }}
          ExitCode: {{ result.container['State']['ExitCode'] }}
          Error: {{ result.container['State']['Error'] }}
      when: result.exists
    - name: Update config.php file - add trusted domain
      debug:
        msg: |
          Ensure following entries are in {{ data_directories[2] }}/config/config.php
          0 => '10.0.0.10:4000',
          1 => 'nextcloud.{{ domain }}',
      tags:
        - message
