---
- name: Traefik config
  hosts: all
  gather_facts: true
  user: przemek
  become: true
  become_user: root

  vars_files:
    - ../../vault.yml
    - vars.yml

  pre_tasks:
    - action: ping

  tasks:
    - name: Update system
      apt:
        name: "*"
        state: latest
        update_cache: yes
        autoremove: yes
    - name: Create traefik log file
      file:
        state: file
        path: "{{ traefik_log_dir }}/traefik.log"
        owner: root
        group: root
        mode: '0740'
    - name: Make tooling direcotry
      file:
        state: directory
        path: "{{ tooling_direcotry }}"
        owner: root
        group: root
        mode: '0750'
    - name: Make traefik directories
      file:
        state: directory
        path: "{{ tooling_direcotry }}/{{ traefik_directory }}"
        owner: root
        group: root
        mode: '0644'
    - name: Copy traefik config file
      ansible.builtin.copy:
        src: ../templates/traefik/traefik.yml
        dest: /etc/traefik/traefik.yml
        owner: root
        group: root
        mode: '0644'
    - name: Setup DNS provider auth variables
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: DYNU_API_KEY={{ DYNU_API_KEY }}
    - name: Create docker network {{ docker_network }}
      docker_network:
        name: "{{ docker_network }}"
    - name: Copy traefik docker-compose file
      template:
        src: ../templates/traefik/traefik.j2
        dest: "{{ tooling_direcotry }}/{{ traefik_directory }}/docker-compose.yml"
        owner: root
        group: root
        mode: '0660'
    - name: Start traefik
      ansible.builtin.shell:
        cmd: docker-compose up -d
        chdir: "{{ tooling_direcotry }}/{{ traefik_directory }}"
    - name: Get {{ traefik_container_name }} container info
      docker_container_info:
        name: "{{ traefik_container_name }}"
      register: result
    - name: Print the status of the {{ traefik_container_name }} container
      debug:
        msg: |
          State: {{ result.container['State']['Status'] }}
      when: result.exists
