# DO NOT CHANGE ORDER OF EXISTING DIRECTORIES LISTS
# IT IS USED IN CODE - {{ data_directories[1] }}
domain: gorillabay.org
docker_network: tooling
traefik_container_name: traefik
tooling_direcotry: /tooling
traefik_directory: traefik
traefik_log_dir: /var/log/traefik

################################
data_directories:
- /samba_shares/tooling/nextcloud
- /samba_shares/tooling/nextcloud/db
- /samba_shares/tooling/nextcloud/data
- /samba_shares/tooling/prometheus
- /samba_shares/tooling/prometheus/data
- /samba_shares/tooling/grafana
- /samba_shares/tooling/grafana/data

############################################## 
monitoring_directories:
- monitoring/prometheus_node_exporter
- monitoring/prometheus_grafana
- monitoring/prometheus_grafana/prometheus_config
prometheus_node_exporter_image: quay.io/prometheus/node-exporter:latest
prometheus_node_exporter_container_name: node_exporter
prometheus_node_exporter_host_port: 9100
prometheus_node_exporter_container_port: 9100

prometheus_image: prom/prometheus:latest
prometheus_container_name: prometheus
prometheus_host_port: 9090
prometheus_container_port: 9090

grafana_image: grafana/grafana:latest
grafana_container_name: grafana
grafana_host_port: 3000
grafana_container_port: 3000

##############################################
nextcloud_directory: nextcloud

nextcloud_db_image: mariadb:10.6
nextcloud_db_container_name: nextcloud_db

nextcloud_app_image: nextcloud
nextcloud_app_container_name: nextcloud_app
nextcloud_host_port: 4000
nextcloud_container_port: 80

##############################################
webpage_directory: webpage
webpage_image: pgorzynski/gorillabay-webpage
webpage_image_version: 26
webpage_container_name: webpage
webpage_host_port: 8082
webpage_container_port: 80