---
- name: Update system
  apt:
    name: "*"
    state: latest
    update_cache: yes
    autoremove: yes
  tags:
   - os_config

- name: Install OS packages
  apt:
    name: "{{ packages }}"
    state: present
  tags:
   - os_config

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
   - os_config

- name: Update /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host].ansible_host }} {{ host }}
      {% endfor %}
  tags:
   - os_config

- name: Update /etc/resolv.conf
  blockinfile:
    path: /etc/resolv.conf
    block: |
      nameserver {{ hostvars['samba'].ansible_host }}
      nameserver 1.1.1.1
  tags:
   - os_config

- name: Update MOTD messages
  block:
    - name: Copy new MOTD script
      copy:
        src: files/motd_11-sysinfo
        dest: /etc/update-motd.d/11-sysinfo
        mode: '0755'
        owner: root
        group: root
    - name: Clean /etc/motd file
      copy:
        content: ""
        dest: /etc/motd
       
- name: Set timezone to Europe/Warsaw
  shell: sudo timedatectl set-timezone "Europe/Warsaw"

- name: Control fan speed
  ansible.builtin.blockinfile:
    path: /boot/config.txt
    block: |
      dtparam=poe_fan_temp0=50000
      dtparam=poe_fan_temp1=60000
      dtparam=poe_fan_temp2=70000
      dtparam=poe_fan_temp3=80000
