#!/bin/sh
BOOT=`df -Ph | grep boot | awk '{ print $3}'`
BOOT_TOTAL=`df -Ph | grep boot | awk '{ print $2}'`
BOOT_FREE=`df -Ph | grep boot | awk '{ print $4}'`
ROOT=`df -Ph | grep root | awk '{ print $3}'`
ROOT_TOTAL=`df -Ph | grep root | awk '{ print $2}'`
ROOT_FREE=`df -Ph | grep root | awk '{ print $4}'`
SDA1=`df -Ph | grep sda1 | awk '{ print $3}'`
SDA1_TOTAL=`df -Ph | grep sda1 | awk '{ print $2}'`
SDA1_FREE=`df -Ph | grep sda1 | awk '{ print $4}'`
SDB1=`df -Ph | grep sdb1 | awk '{ print $3}'`
SDB1_TOTAL=`df -Ph | grep sdb1 | awk '{ print $2}'`
SDB1_FREE=`df -Ph | grep sdb1 | awk '{ print $4}'`
MEMORY1=`free -t -m | grep "Mem" | awk '{print $3" MB";}'`
MEMORY2=`free -t -m | grep "Mem" | awk '{print $2" MB";}'`
RELEASE=`cat /etc/os-release | head -n 1 | awk -F "\"" '{print $2}'`
MONITORING_CONTAINER=`sudo docker ps -a | grep prometheus_node_exporter | awk '{ print $8 " " $9 " " $10 }'`
#System uptime
uptime=`cat /proc/uptime | cut -f1 -d.`
upDays=$((uptime/60/60/24))
upHours=$((uptime/60/60%24))
upMins=$((uptime/60%60))
upSecs=$((uptime%60))

echo "
 - OS Release:.............: $RELEASE
 - System uptime...........: $upDays days $upHours hours $upMins minutes $upSecs seconds
 - Monitoring container....: $MONITORING_CONTAINER
 - Memory used.............: $MEMORY1 / $MEMORY2 used
 - SD /boot space..........: $BOOT  / $BOOT_TOTAL used; $BOOT_FREE Free
 - SD / space..............: $ROOT / $ROOT_TOTAL used; $ROOT_FREE Free
 - SDA disk space..........: `if [ $SDA1 > 0 ]; then echo "$SDA1 / $SDA1_TOTAL used; $SDA1_FREE Free"; else echo "SDA disk not mounted"; fi`
 - SDB disk space..........: `if [ $SDB1 > 0 ]; then echo "$SDB1 / $SDB1_TOTAL used; $SDB1_FREE Free"; else echo "SDB disk not mounted"; fi`
"