---
- name: Base config
  hosts: all
  gather_facts: true
  user: pi
  become: true

  vars_files:
    - ../../vault.yml

  pre_tasks:
    - action: ping

  tasks:
    - import_role:
        name: user_mgmnt
        tasks_from: main.yml
    - import_role:
        name: system_config
        tasks_from: main.yml
    - import_role:
        name: reboot
        tasks_from: main.yml
