---
- name: Base config
  hosts: all
  gather_facts: yes
  user: pi
  become: yes
  
  vars_files:
  -  ../../vault.yml
  
  pre_tasks:
  - name: check connectivity
    ping:

  tasks:
  - import_role:
      name: user_mgmnt
      tasks_from: main.yml
  - import_role:
      name: system_config
      tasks_from: main.yml
  - import_role:
      name: reboot
      tasks_from: main.yml