- name: Copy compose file from template
  template:
    src: ../templates/compose.j2
    dest: /compose/docker-compose.yml
    force: yes

- name: Copy DB config
  copy:
    src: ../../db/01-init.sh
    dest: /compose/db/01-init.sh
    mode: '0664'
    force: yes

- name: Deploy Docker Compose stack
  shell: cd /compose && docker-compose up -d

- name: Check compose stack is deployed
  shell: docker ps -a
  register: docker_status

- name: Docker status
  debug:
    msg:  "{{ docker_status.stdout_lines }}"
  tags:
    - general_config_ubunt