version: '3.8'

networks: 
  tooling:
    external: true
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - tooling
    ports:
      - "9090:9090"
    volumes:
      - /monitoring/prometheus_grafana/prometheus_config:/etc/prometheus
      - /monitoring/prometheus_grafana/prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - tooling
    volumes:
      - "/monitoring/prometheus_grafana/grafana_data:/var/lib/grafana:rw"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.pgorzynski.freeddns.org`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=production"