---
- name: Create data directories
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ directories }}"

- name: Set 777 mode on data directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items: "{{ directories_rwx }}"

- name: Copy prometheus config file
  template:
    src: ../templates/prometheus.yml
    dest: "{{ prometheus_config }}"

- name: Copy Docker compose file prometheus server + grafana
  template:
    src: ../templates/prometheus_grafans_compose.j2
    dest: "{{ compose_dir }}/docker-compose.yml"
    force: yes

- name: Deploy Docker Compose stack
  shell: cd {{ compose_dir }} && docker-compose up -d

- name: Check compose stack is deployed
  shell: docker ps -a
  register: docker_status

- name: Docker status
  debug:
    msg:  "{{ docker_status.stdout_lines }}"