# copy this file into /monitoring/prometheus_config
---
global:
  scrape_interval: 1m
  scrape_timeout: 30s
  evaluation_interval: 1m
  external_labels:
    network: 'home'
scrape_configs:
  - job_name: 'nodes'
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - '10.0.0.10:9100'    # SAMBA
