---
- name: Create prometheus data directory
  file:
    path: "{{ prometheus_dir }}"
    state: directory

- name: Copy prometheus config
  template:
    src: ../templates/prometheus.yml
    dest: "{{ prometheus_dir }}"

- name: Run prometheus server docker service
  community.docker.docker_container:
    name: prometheus
    image: "{{ prometheus_image }}"
    restart: yes
    state: started
    detach: yes
    tty: yes
    mounts:
      source: "{{ prometheus_dir }}"
      target: /etc/prometheus
    ports:
    - "9090:9090"