version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /monitoring/prometheus_grafana/prometheus_config:/etc/prometheus
      - /monitoring/prometheus_grafana/prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "/monitoring/prometheus_grafana/grafana_data:/var/lib/grafana:rw"
    restart: unless-stopped