---
- name: create admin group
  group:
    name: admins
    state: present
  tags:
    - user_config

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell:  "{{ item.shell }}"
    groups: "{{ item.groups }}"
    create_home: yes
  loop:
    - { name: 'przemek', groups: 'sudo,admins', shell: '/bin/bash' }
  tags:
    - user_config

- name: Update przemek user authorized keys
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '../files/id_rsa_przemek.pub') }}"
  with_items:
    - przemek
    - pi
  tags:
    - user_config

- name: Allow sudo for admins group
  copy:
    content: "%admins ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/admins
    mode: 0600
  tags:
    - user_config