---
- name: Update system
  apt:
    name: "*"
    state: latest
    update_cache: true
    autoremove: true
  tags:
    - samba_config

- name: Install Samba packages
  apt:
    name: "{{ packages }}"
    state: present
  tags:
    - samba_config

- name: Create samba read_only user
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    state: present
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    create_home: true
  no_log: true
  loop:
    - {name: 'ro', password: "{{ ro_pass }}", groups: 'users', shell: '/bin/false'}
  tags:
    - samba_config

- name: Create Samba shares
  file:
    state: directory
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: '0777'
  with_items:
    - "{{ samba_shares_root_dir }}"
    - "{{ backup_samba_shares_root_dir }}"
  tags:
    - samba_config

- name: mount Hard Drive for Samba
  mount:
    path: "{{ samba_shares_root_dir }}"
    src: "UUID={{ main_disk_partition }}"
    state: present
    fstype: ext4
    opts: defaults,nofail
  tags:
    - samba_config

- name: mount Backup Hard Drive for Samba
  mount:
    path: "{{ backup_samba_shares_root_dir }}"
    src: "UUID={{ backup_disk_partition }}"
    state: present
    fstype: ext4
    opts: defaults,nofail
  tags:
    - samba_config

- name: Refrest mount drives
  shell: mount -a
  tags:
    - samba_config

- name: Create share directories
  file:
    state: directory
    path: "{{ samba_shares_root_dir }}/{{ item }}"
    owner: www-data
    group: www-data
    mode: '2770'
  with_items: "{{ samba_shares }}"
  tags:
    - samba_config

- name: Create share backup directories
  file:
    state: directory
    path: "{{ backup_samba_shares_root_dir }}/{{ item }}"
    owner: www-data
    group: www-data
    mode: '2770'
  with_items: "{{ samba_backup_shares }}"
  tags:
    - samba_config

- name: Copy Samba config file
  template:
    src: ../templates/smb.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0660'
  tags:
    - samba_config

- name: Restart samba
  service:
    name: smbd
    state: restarted
  tags:
    - samba_config

- name: Update samba password
  shell: |
    echo "{{ przemek_pass }}\n{{ przemek_pass }}" | smbpasswd -a przemek
    echo "{{ ro_pass }}\n{{ ro_pass }}" | smbpasswd -a ro
  tags:
    - samba_config

- name: UFW enable samba
  shell: ufw allow samba
  tags:
    - samba_config

- name: Create Rsync log file
  file:
    state: touch
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0660'
  with_items:
    - "{{ samba_rsync_logfile }}"
  tags:
    - samba_config

- name: Copy Rsync script
  template:
    src: ../templates/rsync.j2
    dest: "{{ samba_rsync_file_path }}"
    owner: root
    group: root
    mode: '0770'
  tags:
    - rsync

- name: set reboot rsync cron task
  ansible.builtin.cron:
    name: "samba rsync at {{ item }}"
    special_time: "{{ item }}"
    job: "{{ samba_rsync_file_path }} 2>&1"
  with_items:
    - reboot
  tags:
    - cron

- name: set custom rsync cron task
  ansible.builtin.cron:
    name: "samba rsync at 6,18"
    minute: "0"
    hour: "6,18"
    job: "{{ samba_rsync_file_path }} 2>&1"
  with_items:
    - reboot
  tags:
    - cron
