---
- name: Samba config
  hosts: all
  gather_facts: yes
  user: przemek
  become: yes
  become_user: root
  
  vars_files:
  -  ../../vault.yml
  
  pre_tasks:
  - name: check connectivity
    ping:

  tasks:
  - import_role:
      name: samba_config
      tasks_from: main.yml
  - import_role:
      name: reboot
      tasks_from: main.yml