---
- name: Samba config
  hosts: all
  gather_facts: true
  user: przemek
  become: true
  become_user: root

  vars_files:
    - ../../vault.yml

  pre_tasks:
    - action: ping

  tasks:
    - import_role:
        name: samba_config
        tasks_from: main.yml
    - import_role:
        name: reboot
        tasks_from: main.yml
