packages:
- samba
- smartmontools

samba_shares_root_dir: /samba_shares
backup_samba_shares_root_dir: /samba_shares_backup

main_disk_partition: 3f3c9183-52ad-4be6-b20b-7d0a0e9b7528
backup_disk_partition: 73962451-806f-4bd0-ac3d-e30b82298e0b

samba_shares:
- mine
- exchange
- foto
- filmy
- inne

samba_backup_shares:
- other