packages:
- samba
- smartmontools

samba_shares_root_dir: /samba_shares
backup_samba_shares_root_dir: /samba_shares_backup

# OLD
# main_disk_partition: 3f3c9183-52ad-4be6-b20b-7d0a0e9b7528  1TB
# backup_disk_partition: 1c5dcb51-59e7-4013-95e2-b2662611ccba 2TB

#NEW
main_disk_partition: 1c5dcb51-59e7-4013-95e2-b2662611ccba  # 2TB
backup_disk_partition: 6e88906f-dafc-476c-8a49-e345710f016f # 4TB


samba_shares:
- mine
- exchange
- foto
- filmy
- inne

samba_backup_shares:
- new
- samba_shares_sync

samba_rsync_logfile: /var/log/rsync.log
samba_rsync_file_path: /rsync.sh
