---
- name: Install OS packages
  apt:
    name: "{{ nextcloud_packages }}"
    state: present
  when: inventory_hostname == "nas"
  tags:
  - pre_config

- name: Create Nextcloud directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /nextcloud
  - /compose
  - /compose/db
  - /compose/nginx
  - /compose/proxy
  tags:
  - pre_config