---
- name: Install OS packages on nextcloud host
  apt:
    name: "{{ nextcloud_packages }}"
    state: present
  when: inventory_hostname == "nextcloud"
  tags:
  - pre_config

- name: Enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  tags:
  - pre_config

- name: Create Netcloud directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /nextcloud
  - /compose
  - /compose/db
  - /compose/nginx
  - /compose/php
  tags:
  - pre_config

- name: Mount Nextcloud storage
  mount:
    path: /nextcloud
    src: "{{ partition_uuid }}"
    fstype: ext4
    opts: noatime
    state: mounted
  tags:
  - pre_config