---
- name: create admin group "admins"
  group:
    name: admins
    state: present
  tags:
    - user_mgmnt

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    state: present
    shell:  "{{ item.shell }}"
    groups: "{{ item.groups }}"
    create_home: yes
  no_log: True
  loop:
    - { name: 'przemek', password: "{{ przemek_pass }}", groups: 'users,sudo,admins,www-data', shell: '/bin/bash' }
  tags:
    - user_mgmnt

- name: Update pi user - add to admin group and update password 
  ansible.builtin.user:
    name: pi
    groups: admins
    append: yes
    password: "{{ pi_pass | password_hash('sha512') }}"
  no_log: True
  tags:
    - user_mgmnt

- name: Update authorized keys
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  with_items:
    - przemek
    - pi
  tags:
    - user_mgmnt

- name: Allow sudo for admins group
  copy:
    content: "%admins ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/admins
    mode: 0600
  tags:
    - user_mgmnt