---
version: '3'

services:
  prometheus:
    image: "{{ prometheus_image }}"
    container_name: "{{ prometheus_container_name }}"
    ports:
      - 9090:9090
    volumes:
      - {{ prometheus_config }}:/etc/prometheus:rw
      - {{ prometheus_data }}:/prometheus:rw
    restart: unless-stopped
  
  grafana:
    image: "{{ grafana_image }}"
    container_name: "{{ grafana_container_name }}"
    ports:
      - 3000:3000
    volumes:
      - {{ grafana_data }}:/var/lib/grafana:rw
    restart: unless-stopped