---
- name: Initiall configuration
  hosts: all
  gather_facts: yes
  user: przemek
  become: yes
  
  pre_tasks:
  - name: check connectivity
    ping:

  tasks:
  - import_role:
      name: omv
      tasks_from: main.yml
  - import_role:
      name: reboot
      tasks_from: main.yml